server:
  port: 9011
spring:
  data:
    mongodb:
      uri: mongodb://maher:maher@localhost:27017/expertsconseil?retryWrites=true&w=majority
      #mongodb://username:password@host1:port1,host2:port2/database?option1=value1&option2=value2
      #uri: mongodb+srv://expertsConseil_db_user:IQ7vInO0QjtrJdDY@expertsconseilcluster.zjjpyjh.mongodb.net/ExpertsConseilCluster?retryWrites=true&w=majority
  boot:
    admin:
      client:
        url: http://localhost:9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

management:
  endpoints:
    web:
      exposure:
        include: 'health, metrics'
  tracing:
    sampling:
      probability: 1.0 
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    
springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt-service:
  secret-key: ce79e749650fb0c8595801d94c222bbc786ccbcf01d50f09cc579cd8b6143e38e8c2d551e658355a7cd819fe424d8a223ceee652edd38cd74f2e2b5da79dadfb91b93f4b03cdb89d410dbf2c9158f5fe75af7380297bc1682e421a204f813b5454e43f746805bf39120dad0f7e06e179d5dfdcc72f9d40371785691a9c8ab8e088f5f39a68a31c45bc1dadd52e6195dc7de9ddf4fb05232baa9ef2a59fb5e3e6397cdbedae47cdf3db0557fe25124714c23babfef3345dfc93e1c01b843e1f2cac326e8d8c0dbb603de9dd1e5d738463c5e94c9c8f68efa0a10f10f095d8a3768e182ed21706b68d3d35d1c30fc25a3990b7e193e0131aa8246748a2aa982463
  token-expiration: 1800
