server:
  port: 9002
spring:
  application:
    name: naming-server
  boot:
    admin:
      client:
        url: http://localhost:9003
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: 'health, metrics'