spring:
  application:
    name: naming-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: 'health, metrics'