logging:
  level:
    root: info
server:
  port: 8013
spring:
  data:
    mongodb:
      uri: mongodb://maher:maher@localhost:27017/expertsconseil?retryWrites=true&w=majority
      #authentication-database: maher
  boot:
    admin:
      client:
        url: http://localhost:8003
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
resilience4j:
  retry:
    instances:
      user-service:
        maxAttempts: 5
        waitDuration: 1s
management:
  endpoints:
    web:
      exposure:
        include: 'health, metrics'
springdoc:
  swagger-ui:
    path: /swagger-ui.html