logging:
  level:
    root: info
server:
  port: 9012
spring:
  application:
    name: quiz-generator
    data:
    mongodb:
      uri: mongodb://maher:maher@localhost:27017/expertsconseil?retryWrites=true&w=majority
  boot:
    admin:
      client:
        url: http://localhost:9003
eureka:
  client:
    serviceUrl:
      defaultzZone: http://localhost:8002/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'health, metrics'
springdoc:
  swagger-ui:
    path: /swagger-ui.html