---
server:
  port: 8012
spring:
  data:
    mongodb:
      uri: mongodb://maher:maher@localhost:27017/expertsconseil?retryWrites=true&w=majority
  boot:
    admin:
      client:
        url: http://localhost:8050
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  tracing:
    sampling:
      probability: 1
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
