logging:
  level:
    root: info
server:
  port: 8011
spring:
  application:
    name: user_service
  data:
    mongodb:
      uri: mongodb://maher:maher@localhost:27017/expertsconseil?retryWrites=true&w=majority
      #authentication-database: maher
  boot:
    admin:
      client:
        url: http://localhost:8003
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'health, metrics'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
